[filename]
filename_pattern = "$date$sep$index$sep$prompt"
use_local_time_zone = true

[collection]
collections_to_include = [ "Pirate",]

[debug]
debug = true
use_log_file = true
debug_filename = "bing_image_creator.log"
